update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Deploy a new beta build to the Google Play Store"
  lane :beta do
    begin
      build_deploy_beta()
    rescue => exception
      on_error(exception)
    end
    
  end
end

def build_deploy_beta
  gradle(
    task: 'assemble',
    build_type: 'Release',
    properties: {     
        "android.injected.signing.store.file" => "keystore.jks",
        "android.injected.signing.store.password" => ENV['KEYSTORE_PASSWORD'],     
        "android.injected.signing.key.alias" => ENV['KEYSTORE_ALIAS'],
        "android.injected.signing.key.password" => ENV['KEYSTORE_ALIAS_PASSWORD'], 
    }
  )
  apk_path = Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
  upload_to_play_store(
  apk: apk_path,
  track: "beta"
  )
  slack(
    message: "Beta build succesfully released on Google Play Store",
    success: true,
    slack_url: "https://hooks.slack.com/services/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"
  )
end

def on_error(exception)
  slack(
    message: "Lane failed with exception : #{exception}",
    success: false,
    slack_url: "https://hooks.slack.com/services/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",
  )
end